/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as NewPatientsRouteImport } from './routes/new-patients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CdcpRouteImport } from './routes/cdcp'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatientsRoute = NewPatientsRouteImport.update({
  id: '/new-patients',
  path: '/new-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CdcpRoute = CdcpRouteImport.update({
  id: '/cdcp',
  path: '/cdcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cdcp': typeof CdcpRoute
  '/contact': typeof ContactRoute
  '/new-patients': typeof NewPatientsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/visit': typeof VisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cdcp': typeof CdcpRoute
  '/contact': typeof ContactRoute
  '/new-patients': typeof NewPatientsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/visit': typeof VisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cdcp': typeof CdcpRoute
  '/contact': typeof ContactRoute
  '/new-patients': typeof NewPatientsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/visit': typeof VisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cdcp'
    | '/contact'
    | '/new-patients'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cdcp'
    | '/contact'
    | '/new-patients'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/visit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cdcp'
    | '/contact'
    | '/new-patients'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CdcpRoute: typeof CdcpRoute
  ContactRoute: typeof ContactRoute
  NewPatientsRoute: typeof NewPatientsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  VisitRoute: typeof VisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patients': {
      id: '/new-patients'
      path: '/new-patients'
      fullPath: '/new-patients'
      preLoaderRoute: typeof NewPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdcp': {
      id: '/cdcp'
      path: '/cdcp'
      fullPath: '/cdcp'
      preLoaderRoute: typeof CdcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CdcpRoute: CdcpRoute,
  ContactRoute: ContactRoute,
  NewPatientsRoute: NewPatientsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  VisitRoute: VisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
