/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as NewPatientsRouteImport } from './routes/new-patients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CdcpRouteImport } from './routes/cdcp'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions.index'
import { Route as QuestionsFirstDentalVisitUnionvilleRouteImport } from './routes/questions/first-dental-visit-unionville'
import { Route as QuestionsCdcpDentistUnionvilleRouteImport } from './routes/questions/cdcp-dentist-unionville'
import { Route as QuestionsBestDentistUnionvilleRouteImport } from './routes/questions/best-dentist-unionville'
import { Route as QuestionsBestDentistMarkhamRouteImport } from './routes/questions/best-dentist-markham'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatientsRoute = NewPatientsRouteImport.update({
  id: '/new-patients',
  path: '/new-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CdcpRoute = CdcpRouteImport.update({
  id: '/cdcp',
  path: '/cdcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestionsRoute,
} as any)
const QuestionsFirstDentalVisitUnionvilleRoute =
  QuestionsFirstDentalVisitUnionvilleRouteImport.update({
    id: '/first-dental-visit-unionville',
    path: '/first-dental-visit-unionville',
    getParentRoute: () => QuestionsRoute,
  } as any)
const QuestionsCdcpDentistUnionvilleRoute =
  QuestionsCdcpDentistUnionvilleRouteImport.update({
    id: '/cdcp-dentist-unionville',
    path: '/cdcp-dentist-unionville',
    getParentRoute: () => QuestionsRoute,
  } as any)
const QuestionsBestDentistUnionvilleRoute =
  QuestionsBestDentistUnionvilleRouteImport.update({
    id: '/best-dentist-unionville',
    path: '/best-dentist-unionville',
    getParentRoute: () => QuestionsRoute,
  } as any)
const QuestionsBestDentistMarkhamRoute =
  QuestionsBestDentistMarkhamRouteImport.update({
    id: '/best-dentist-markham',
    path: '/best-dentist-markham',
    getParentRoute: () => QuestionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cdcp': typeof CdcpRoute
  '/contact': typeof ContactRoute
  '/new-patients': typeof NewPatientsRoute
  '/questions': typeof QuestionsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/visit': typeof VisitRoute
  '/questions/best-dentist-markham': typeof QuestionsBestDentistMarkhamRoute
  '/questions/best-dentist-unionville': typeof QuestionsBestDentistUnionvilleRoute
  '/questions/cdcp-dentist-unionville': typeof QuestionsCdcpDentistUnionvilleRoute
  '/questions/first-dental-visit-unionville': typeof QuestionsFirstDentalVisitUnionvilleRoute
  '/questions/': typeof QuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cdcp': typeof CdcpRoute
  '/contact': typeof ContactRoute
  '/new-patients': typeof NewPatientsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/visit': typeof VisitRoute
  '/questions/best-dentist-markham': typeof QuestionsBestDentistMarkhamRoute
  '/questions/best-dentist-unionville': typeof QuestionsBestDentistUnionvilleRoute
  '/questions/cdcp-dentist-unionville': typeof QuestionsCdcpDentistUnionvilleRoute
  '/questions/first-dental-visit-unionville': typeof QuestionsFirstDentalVisitUnionvilleRoute
  '/questions': typeof QuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cdcp': typeof CdcpRoute
  '/contact': typeof ContactRoute
  '/new-patients': typeof NewPatientsRoute
  '/questions': typeof QuestionsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/visit': typeof VisitRoute
  '/questions/best-dentist-markham': typeof QuestionsBestDentistMarkhamRoute
  '/questions/best-dentist-unionville': typeof QuestionsBestDentistUnionvilleRoute
  '/questions/cdcp-dentist-unionville': typeof QuestionsCdcpDentistUnionvilleRoute
  '/questions/first-dental-visit-unionville': typeof QuestionsFirstDentalVisitUnionvilleRoute
  '/questions/': typeof QuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cdcp'
    | '/contact'
    | '/new-patients'
    | '/questions'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/visit'
    | '/questions/best-dentist-markham'
    | '/questions/best-dentist-unionville'
    | '/questions/cdcp-dentist-unionville'
    | '/questions/first-dental-visit-unionville'
    | '/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cdcp'
    | '/contact'
    | '/new-patients'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/visit'
    | '/questions/best-dentist-markham'
    | '/questions/best-dentist-unionville'
    | '/questions/cdcp-dentist-unionville'
    | '/questions/first-dental-visit-unionville'
    | '/questions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cdcp'
    | '/contact'
    | '/new-patients'
    | '/questions'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/visit'
    | '/questions/best-dentist-markham'
    | '/questions/best-dentist-unionville'
    | '/questions/cdcp-dentist-unionville'
    | '/questions/first-dental-visit-unionville'
    | '/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CdcpRoute: typeof CdcpRoute
  ContactRoute: typeof ContactRoute
  NewPatientsRoute: typeof NewPatientsRoute
  QuestionsRoute: typeof QuestionsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  VisitRoute: typeof VisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patients': {
      id: '/new-patients'
      path: '/new-patients'
      fullPath: '/new-patients'
      preLoaderRoute: typeof NewPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdcp': {
      id: '/cdcp'
      path: '/cdcp'
      fullPath: '/cdcp'
      preLoaderRoute: typeof CdcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/first-dental-visit-unionville': {
      id: '/questions/first-dental-visit-unionville'
      path: '/first-dental-visit-unionville'
      fullPath: '/questions/first-dental-visit-unionville'
      preLoaderRoute: typeof QuestionsFirstDentalVisitUnionvilleRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/cdcp-dentist-unionville': {
      id: '/questions/cdcp-dentist-unionville'
      path: '/cdcp-dentist-unionville'
      fullPath: '/questions/cdcp-dentist-unionville'
      preLoaderRoute: typeof QuestionsCdcpDentistUnionvilleRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/best-dentist-unionville': {
      id: '/questions/best-dentist-unionville'
      path: '/best-dentist-unionville'
      fullPath: '/questions/best-dentist-unionville'
      preLoaderRoute: typeof QuestionsBestDentistUnionvilleRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/best-dentist-markham': {
      id: '/questions/best-dentist-markham'
      path: '/best-dentist-markham'
      fullPath: '/questions/best-dentist-markham'
      preLoaderRoute: typeof QuestionsBestDentistMarkhamRouteImport
      parentRoute: typeof QuestionsRoute
    }
  }
}

interface QuestionsRouteChildren {
  QuestionsBestDentistMarkhamRoute: typeof QuestionsBestDentistMarkhamRoute
  QuestionsBestDentistUnionvilleRoute: typeof QuestionsBestDentistUnionvilleRoute
  QuestionsCdcpDentistUnionvilleRoute: typeof QuestionsCdcpDentistUnionvilleRoute
  QuestionsFirstDentalVisitUnionvilleRoute: typeof QuestionsFirstDentalVisitUnionvilleRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
}

const QuestionsRouteChildren: QuestionsRouteChildren = {
  QuestionsBestDentistMarkhamRoute: QuestionsBestDentistMarkhamRoute,
  QuestionsBestDentistUnionvilleRoute: QuestionsBestDentistUnionvilleRoute,
  QuestionsCdcpDentistUnionvilleRoute: QuestionsCdcpDentistUnionvilleRoute,
  QuestionsFirstDentalVisitUnionvilleRoute:
    QuestionsFirstDentalVisitUnionvilleRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
}

const QuestionsRouteWithChildren = QuestionsRoute._addFileChildren(
  QuestionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CdcpRoute: CdcpRoute,
  ContactRoute: ContactRoute,
  NewPatientsRoute: NewPatientsRoute,
  QuestionsRoute: QuestionsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  VisitRoute: VisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
