/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PatientRightsRouteImport } from './routes/patient-rights'
import { Route as NewPatientsRouteImport } from './routes/new-patients'
import { Route as FrRouteImport } from './routes/fr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CdcpRouteImport } from './routes/cdcp'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions.index'
import { Route as QuestionsMarkhamAreaDentalOfficeRouteImport } from './routes/questions/markham-area-dental-office'
import { Route as QuestionsFirstDentalVisitUnionvilleRouteImport } from './routes/questions/first-dental-visit-unionville'
import { Route as QuestionsChooseFamilyDentistUnionvilleRouteImport } from './routes/questions/choose-family-dentist-unionville'
import { Route as QuestionsCdcpDentistUnionvilleRouteImport } from './routes/questions/cdcp-dentist-unionville'

const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRightsRoute = PatientRightsRouteImport.update({
  id: '/patient-rights',
  path: '/patient-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatientsRoute = NewPatientsRouteImport.update({
  id: '/new-patients',
  path: '/new-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CdcpRoute = CdcpRouteImport.update({
  id: '/cdcp',
  path: '/cdcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestionsRoute,
} as any)
const QuestionsMarkhamAreaDentalOfficeRoute =
  QuestionsMarkhamAreaDentalOfficeRouteImport.update({
    id: '/markham-area-dental-office',
    path: '/markham-area-dental-office',
    getParentRoute: () => QuestionsRoute,
  } as any)
const QuestionsFirstDentalVisitUnionvilleRoute =
  QuestionsFirstDentalVisitUnionvilleRouteImport.update({
    id: '/first-dental-visit-unionville',
    path: '/first-dental-visit-unionville',
    getParentRoute: () => QuestionsRoute,
  } as any)
const QuestionsChooseFamilyDentistUnionvilleRoute =
  QuestionsChooseFamilyDentistUnionvilleRouteImport.update({
    id: '/choose-family-dentist-unionville',
    path: '/choose-family-dentist-unionville',
    getParentRoute: () => QuestionsRoute,
  } as any)
const QuestionsCdcpDentistUnionvilleRoute =
  QuestionsCdcpDentistUnionvilleRouteImport.update({
    id: '/cdcp-dentist-unionville',
    path: '/cdcp-dentist-unionville',
    getParentRoute: () => QuestionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/cdcp': typeof CdcpRoute
  '/contact': typeof ContactRoute
  '/fr': typeof FrRoute
  '/new-patients': typeof NewPatientsRoute
  '/patient-rights': typeof PatientRightsRoute
  '/privacy': typeof PrivacyRoute
  '/questions': typeof QuestionsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/visit': typeof VisitRoute
  '/zh': typeof ZhRoute
  '/questions/cdcp-dentist-unionville': typeof QuestionsCdcpDentistUnionvilleRoute
  '/questions/choose-family-dentist-unionville': typeof QuestionsChooseFamilyDentistUnionvilleRoute
  '/questions/first-dental-visit-unionville': typeof QuestionsFirstDentalVisitUnionvilleRoute
  '/questions/markham-area-dental-office': typeof QuestionsMarkhamAreaDentalOfficeRoute
  '/questions/': typeof QuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/cdcp': typeof CdcpRoute
  '/contact': typeof ContactRoute
  '/fr': typeof FrRoute
  '/new-patients': typeof NewPatientsRoute
  '/patient-rights': typeof PatientRightsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/visit': typeof VisitRoute
  '/zh': typeof ZhRoute
  '/questions/cdcp-dentist-unionville': typeof QuestionsCdcpDentistUnionvilleRoute
  '/questions/choose-family-dentist-unionville': typeof QuestionsChooseFamilyDentistUnionvilleRoute
  '/questions/first-dental-visit-unionville': typeof QuestionsFirstDentalVisitUnionvilleRoute
  '/questions/markham-area-dental-office': typeof QuestionsMarkhamAreaDentalOfficeRoute
  '/questions': typeof QuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/cdcp': typeof CdcpRoute
  '/contact': typeof ContactRoute
  '/fr': typeof FrRoute
  '/new-patients': typeof NewPatientsRoute
  '/patient-rights': typeof PatientRightsRoute
  '/privacy': typeof PrivacyRoute
  '/questions': typeof QuestionsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/visit': typeof VisitRoute
  '/zh': typeof ZhRoute
  '/questions/cdcp-dentist-unionville': typeof QuestionsCdcpDentistUnionvilleRoute
  '/questions/choose-family-dentist-unionville': typeof QuestionsChooseFamilyDentistUnionvilleRoute
  '/questions/first-dental-visit-unionville': typeof QuestionsFirstDentalVisitUnionvilleRoute
  '/questions/markham-area-dental-office': typeof QuestionsMarkhamAreaDentalOfficeRoute
  '/questions/': typeof QuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/cdcp'
    | '/contact'
    | '/fr'
    | '/new-patients'
    | '/patient-rights'
    | '/privacy'
    | '/questions'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/visit'
    | '/zh'
    | '/questions/cdcp-dentist-unionville'
    | '/questions/choose-family-dentist-unionville'
    | '/questions/first-dental-visit-unionville'
    | '/questions/markham-area-dental-office'
    | '/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/cdcp'
    | '/contact'
    | '/fr'
    | '/new-patients'
    | '/patient-rights'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/visit'
    | '/zh'
    | '/questions/cdcp-dentist-unionville'
    | '/questions/choose-family-dentist-unionville'
    | '/questions/first-dental-visit-unionville'
    | '/questions/markham-area-dental-office'
    | '/questions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/cdcp'
    | '/contact'
    | '/fr'
    | '/new-patients'
    | '/patient-rights'
    | '/privacy'
    | '/questions'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/visit'
    | '/zh'
    | '/questions/cdcp-dentist-unionville'
    | '/questions/choose-family-dentist-unionville'
    | '/questions/first-dental-visit-unionville'
    | '/questions/markham-area-dental-office'
    | '/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CdcpRoute: typeof CdcpRoute
  ContactRoute: typeof ContactRoute
  FrRoute: typeof FrRoute
  NewPatientsRoute: typeof NewPatientsRoute
  PatientRightsRoute: typeof PatientRightsRoute
  PrivacyRoute: typeof PrivacyRoute
  QuestionsRoute: typeof QuestionsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  VisitRoute: typeof VisitRoute
  ZhRoute: typeof ZhRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-rights': {
      id: '/patient-rights'
      path: '/patient-rights'
      fullPath: '/patient-rights'
      preLoaderRoute: typeof PatientRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patients': {
      id: '/new-patients'
      path: '/new-patients'
      fullPath: '/new-patients'
      preLoaderRoute: typeof NewPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdcp': {
      id: '/cdcp'
      path: '/cdcp'
      fullPath: '/cdcp'
      preLoaderRoute: typeof CdcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/markham-area-dental-office': {
      id: '/questions/markham-area-dental-office'
      path: '/markham-area-dental-office'
      fullPath: '/questions/markham-area-dental-office'
      preLoaderRoute: typeof QuestionsMarkhamAreaDentalOfficeRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/first-dental-visit-unionville': {
      id: '/questions/first-dental-visit-unionville'
      path: '/first-dental-visit-unionville'
      fullPath: '/questions/first-dental-visit-unionville'
      preLoaderRoute: typeof QuestionsFirstDentalVisitUnionvilleRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/choose-family-dentist-unionville': {
      id: '/questions/choose-family-dentist-unionville'
      path: '/choose-family-dentist-unionville'
      fullPath: '/questions/choose-family-dentist-unionville'
      preLoaderRoute: typeof QuestionsChooseFamilyDentistUnionvilleRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/cdcp-dentist-unionville': {
      id: '/questions/cdcp-dentist-unionville'
      path: '/cdcp-dentist-unionville'
      fullPath: '/questions/cdcp-dentist-unionville'
      preLoaderRoute: typeof QuestionsCdcpDentistUnionvilleRouteImport
      parentRoute: typeof QuestionsRoute
    }
  }
}

interface QuestionsRouteChildren {
  QuestionsCdcpDentistUnionvilleRoute: typeof QuestionsCdcpDentistUnionvilleRoute
  QuestionsChooseFamilyDentistUnionvilleRoute: typeof QuestionsChooseFamilyDentistUnionvilleRoute
  QuestionsFirstDentalVisitUnionvilleRoute: typeof QuestionsFirstDentalVisitUnionvilleRoute
  QuestionsMarkhamAreaDentalOfficeRoute: typeof QuestionsMarkhamAreaDentalOfficeRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
}

const QuestionsRouteChildren: QuestionsRouteChildren = {
  QuestionsCdcpDentistUnionvilleRoute: QuestionsCdcpDentistUnionvilleRoute,
  QuestionsChooseFamilyDentistUnionvilleRoute:
    QuestionsChooseFamilyDentistUnionvilleRoute,
  QuestionsFirstDentalVisitUnionvilleRoute:
    QuestionsFirstDentalVisitUnionvilleRoute,
  QuestionsMarkhamAreaDentalOfficeRoute: QuestionsMarkhamAreaDentalOfficeRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
}

const QuestionsRouteWithChildren = QuestionsRoute._addFileChildren(
  QuestionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CdcpRoute: CdcpRoute,
  ContactRoute: ContactRoute,
  FrRoute: FrRoute,
  NewPatientsRoute: NewPatientsRoute,
  PatientRightsRoute: PatientRightsRoute,
  PrivacyRoute: PrivacyRoute,
  QuestionsRoute: QuestionsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  VisitRoute: VisitRoute,
  ZhRoute: ZhRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
